# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2aaa47c2-bf83-4118-9f34-067986eed708";
      fsType = "btrfs";
      options = [
        "noatime"
	"nodiratime"
	"compress=lzo"
	"discard"
      ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/b6b11b9c-a707-4af6-b996-dd3b1702cfcc";

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/83d013c5-384c-4b56-a319-70a51bcd9bec";
      fsType = "btrfs";
      options = [
        "noatime"
	"nodiratime"
	"compress=lzo"
	"discard"
      ];
    };

  boot.initrd.luks.devices."cryptdata".device = "/dev/disk/by-uuid/bd48c0b7-ac70-4b97-b3bc-010938e1d227";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/99d42c25-0c14-41d2-abd8-5ac25d3e97bc";
      fsType = "btrfs";
      options = [
        "noatime"
	"nodiratime"
	"compress=lzo"
	"discard"
      ];
    };

  boot.initrd.luks.devices."crypthome".device = "/dev/disk/by-uuid/2dbcd1df-b09e-4cc7-a40e-e400e933839c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/60BA-7741";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
