# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.initrd.luks.devices."crypt-root".device = "/dev/disk/by-uuid/ffcf0e8d-544f-483c-b33f-b6bd3979e92c";
  boot.initrd.luks.devices."crypt-home".device = "/dev/disk/by-uuid/882d7f4c-b97c-4e09-9127-ced4a47f626a";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/23B5-2E98";
      fsType = "vfat";
    };

  fileSystems."/" =
    { device = "/dev/mapper/crypt-root";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/3aa1e040-c93f-447c-b982-4a8f0a18cd73";
      fsType = "btrfs";
    };


  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
