# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/de8fd8e7-7135-494d-9a5f-8fa65a090832";
      fsType = "btrfs";
      options = [ "compress" "noatime" ];
    };

  boot.initrd.luks.devices."crypt-root".device = "/dev/disk/by-uuid/69473814-9a81-4094-b66c-9fff21f70ca1";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e9105016-5b05-4545-96cc-c934a58f7524";
      fsType = "btrfs";
      options = [ "compress" "noatime" ];
    };

  boot.initrd.luks.devices."crypt-home".device = "/dev/disk/by-uuid/31ac64ac-30aa-4ebf-86d2-a430f68a0452";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0227-1E5A";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
